# Generated by Django 2.2.12 on 2020-10-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Color', models.CharField(max_length=20)),
                ('Pet', models.CharField(choices=[('cat', 'Cats'), ('dog', 'Dogs')], default='cat', max_length=10)),
            ],
        ),
    ]
