name: ContainerBuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1


        - name: Check out the repo
          uses: actions/checkout@v2
        
        - name: Get short SHA for commit
          id: shortsha
          run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
  
        - name: Get short repo name
          id: shortrepo
          run: echo "::set-output name=reposlug::$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f2)"

        - name: Build and push container
          uses: actions/checkout@v2
          run: |
            echo "${{ secrets.GH_DOCKER.PAT }}" | docker login https://docker.pkg.github.com/ -u ${{ github.repository_owner }} --password-stdin
            docker build -t docker.pkg.github.com/${{ github.repository }}/${{ steps.shortrepo.outputs.reposlug }}:${{ steps.shortsha.outputs.sha8 }}
            docker push -t docker.pkg.github.com/${{ github.repository }}/${{ steps.shortrepo.outputs.reposlug }}:${{ steps.shortsha.outputs.sha8 }}